version: '3'
x-airflow-common: &airflow-common
  image: apache/airflow:2.9.2
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=false
    - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}"

services:
airflow-init:
  <<: *airflow-common
  container_name: airflow_init
  entrypoint: /bin/bash
  command:
    - -c
    - exec /entrypoint airflow db init
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-init
    command: airflow scheduler